version: '3.8'

volumes:
  grafana:
  prometheus:

services:
  exporter:
    image: prom/node-exporter:latest
    container_name: exporter
    network_mode: host
    pid: host
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    expose:
      - 9100
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.5G
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9100 || exit
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    pid: host
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 0.5G
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9090 || exit
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      exporter:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    network_mode: host
    pid: host
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitoring/main-dashboard.json:/var/lib/grafana/dashboards/main-dashboard.json
      - ./monitoring/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - grafana:/var/lib/grafana
    expose:
      - 3000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:3000 || exit
      interval: 5s
      timeout: 5s
      retries: 5
