{
 "title": "PostgreSQL Metrics (postgres exporter)",
 "description": "PostgreSQL Performance Metrics",
 "tags": [ "postgresql" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "database", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table cache hit rates",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT sum(heap_blks_read) as heap_read, sum(heap_blks_hit)  as heap_hit, (sum(heap_blks_hit) - sum(heap_blks_read)) / sum(heap_blks_hit) as ratio\nFROM pg_statio_user_tables"
    }
   ]
  },
  {
   "title": "Index cache hit rates",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n        sum(idx_blks_read) AS idx_read,\n        sum(idx_blks_hit) AS idx_hit,\n        (sum(idx_blks_hit) - sum(idx_blks_read)) / sum(idx_blks_hit) AS ratio\nFROM\n        pg_statio_user_indexes"
    }
   ]
  },
  {
   "title": "Table index usage rates",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT schemaname AS \"Schema\",\n       relname AS \"Relation\", \n  CASE WHEN (seq_scan + idx_scan) != 0\n    THEN 100.0 * idx_scan / (seq_scan + idx_scan) \n    ELSE 0\n  END AS percent_of_times_index_used,\n  n_live_tup AS rows_in_table\nFROM\n        pg_stat_user_tables \nWHERE\n        n_live_tup > 0\nORDER BY n_live_tup DESC"
    }
   ]
  },
  { "title": "Querys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Running queries",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT pid, age(query_start, clock_timestamp()), usename, client_hostname, application_name, query \nFROM pg_stat_activity \nWHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%' AND query NOT ILIKE '' \nORDER BY query_start desc;"
    }
   ]
  },
  {
   "title": "Disk storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database size",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT d.datname AS Name, pg_catalog.pg_get_userbyid(d.datdba) AS Owner,\n  CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT')\n    THEN pg_catalog.pg_size_pretty(pg_catalog.pg_database_size(d.datname)) \n    ELSE 'No Access' \n  END AS SIZE \nFROM pg_catalog.pg_database d \nORDER BY \n  CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') \n    THEN pg_catalog.pg_database_size(d.datname)\n    ELSE NULL \n  END"
    }
   ]
  },
  {
   "title": "Table size",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n        nspname AS \"Scheme\",\n        relname AS \"Relation\",\n        pg_total_relation_size(C.oid) AS \"total_size\"\nFROM\n        pg_class C\nLEFT JOIN\n        pg_namespace N ON (N.oid = C.relnamespace)\nWHERE\n        nspname NOT IN ('pg_catalog', 'information_schema')\nAND\n        C.relkind <> 'i'\nAND\n        nspname !~ '^pg_toast'\nORDER BY\n        pg_total_relation_size(C.oid) DESC"
    }
   ]
  },
  {
   "title": "Table disk level",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n        schemaname AS \"Schema\",\n        relname AS \"Relation\",\n        last_vacuum,\n        last_autovacuum,\n        last_analyze,\n        last_autoanalyze,\n        n_live_tup,\n        n_dead_tup,\n        n_live_tup * 100. / ( n_live_tup + n_dead_tup) AS level\nfrom\n        pg_stat_user_tables\nwhere\n        n_dead_tup > 0\norder by\n        n_dead_tup desc"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Locks",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT t.relname, l.locktype, virtualtransaction, pid, mode, granted \nFROM pg_locks l, pg_stat_all_tables t \nWHERE l.relation = t.relid ORDER BY relation asc"
    }
   ]
  },
  {
   "title": "Users and Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n       *\nfrom\n      pg_user"
    }
   ]
  },
  {
   "title": "Connections per user",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select usename, count(usename) as connections from pg_stat_activity where query not like '' group by usename order by connections desc"
    }
   ]
  }
 ]
}